# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug

build:
  verbosity: minimal
  parallel: true

# to run your custom scripts instead of automatic tests
test_script:
  #- dir PortableApps\pCLI\Other\Source\_Solution_\Deliverable\x64\Debug\
  #- dir PortableApps\pCLI\Other\Source\_Solution_\Deliverable\x64\Debug\testCommon.exe
  - PortableApps\pCLI\Other\Source\_Solution_\Deliverable\x64\Debug\testCommon.exe
