version: "{build}"

os: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug

build:
  verbosity: minimal
  parallel: true

test_script:  
  - PortableApps\pCLI\Other\Source\_Solution_\Deliverable\Win32\Debug\testCommon.exe
